//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/[assets]/VRInputAsset.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @VRInputAsset: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @VRInputAsset()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""VRInputAsset"",
    ""maps"": [
        {
            ""name"": ""VRInput"",
            ""id"": ""ab014218-38d3-46ee-8b02-077943d0c46b"",
            ""actions"": [
                {
                    ""name"": ""LeftThumbstick"",
                    ""type"": ""Value"",
                    ""id"": ""9ac8ff50-fa96-48fe-8f58-af7881d713c2"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightThumbstick"",
                    ""type"": ""Value"",
                    ""id"": ""3447b00d-80af-465c-b69d-6e4c16ec4bbf"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7ff36ba9-8332-4235-b8d8-066be77a1a0a"",
                    ""path"": ""<XRController>{LeftHand}/{Primary2DAxis}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftThumbstick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fcbfac58-b5a6-4d7a-b9a3-abba502c583c"",
                    ""path"": ""<XRController>{RightHand}/{Primary2DAxis}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightThumbstick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // VRInput
        m_VRInput = asset.FindActionMap("VRInput", throwIfNotFound: true);
        m_VRInput_LeftThumbstick = m_VRInput.FindAction("LeftThumbstick", throwIfNotFound: true);
        m_VRInput_RightThumbstick = m_VRInput.FindAction("RightThumbstick", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // VRInput
    private readonly InputActionMap m_VRInput;
    private List<IVRInputActions> m_VRInputActionsCallbackInterfaces = new List<IVRInputActions>();
    private readonly InputAction m_VRInput_LeftThumbstick;
    private readonly InputAction m_VRInput_RightThumbstick;
    public struct VRInputActions
    {
        private @VRInputAsset m_Wrapper;
        public VRInputActions(@VRInputAsset wrapper) { m_Wrapper = wrapper; }
        public InputAction @LeftThumbstick => m_Wrapper.m_VRInput_LeftThumbstick;
        public InputAction @RightThumbstick => m_Wrapper.m_VRInput_RightThumbstick;
        public InputActionMap Get() { return m_Wrapper.m_VRInput; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(VRInputActions set) { return set.Get(); }
        public void AddCallbacks(IVRInputActions instance)
        {
            if (instance == null || m_Wrapper.m_VRInputActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_VRInputActionsCallbackInterfaces.Add(instance);
            @LeftThumbstick.started += instance.OnLeftThumbstick;
            @LeftThumbstick.performed += instance.OnLeftThumbstick;
            @LeftThumbstick.canceled += instance.OnLeftThumbstick;
            @RightThumbstick.started += instance.OnRightThumbstick;
            @RightThumbstick.performed += instance.OnRightThumbstick;
            @RightThumbstick.canceled += instance.OnRightThumbstick;
        }

        private void UnregisterCallbacks(IVRInputActions instance)
        {
            @LeftThumbstick.started -= instance.OnLeftThumbstick;
            @LeftThumbstick.performed -= instance.OnLeftThumbstick;
            @LeftThumbstick.canceled -= instance.OnLeftThumbstick;
            @RightThumbstick.started -= instance.OnRightThumbstick;
            @RightThumbstick.performed -= instance.OnRightThumbstick;
            @RightThumbstick.canceled -= instance.OnRightThumbstick;
        }

        public void RemoveCallbacks(IVRInputActions instance)
        {
            if (m_Wrapper.m_VRInputActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IVRInputActions instance)
        {
            foreach (var item in m_Wrapper.m_VRInputActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_VRInputActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public VRInputActions @VRInput => new VRInputActions(this);
    public interface IVRInputActions
    {
        void OnLeftThumbstick(InputAction.CallbackContext context);
        void OnRightThumbstick(InputAction.CallbackContext context);
    }
}
